theme: minima
title: Hello world
author: hwemudua57
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first Github pages site!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
